frappe.query_reports["Cash Budget"] = {
	filters: [
		{
			fieldname: "company",
			label: __("Company"),
			fieldtype: "Link",
			options: "Company",
			reqd: 1,
			default: frappe.defaults.get_user_default("Company"),
		},
		{
			fieldname: "report_scope",
			label: __("Report Scope"),
			fieldtype: "Select",
			options: "Single Company\nConsolidated Group",
			default: "Single Company",
			reqd: 1,
		},
		{
			fieldname: "from_date",
			label: __("From Date"),
			fieldtype: "Date",
			reqd: 1,
		},
		{
			fieldname: "to_date",
			label: __("To Date"),
			fieldtype: "Date",
			reqd: 1,
		},
		{
			fieldname: "include_parent_company_entries",
			label: __("Include Parent Company Entries"),
			fieldtype: "Check",
			default: 0,
			depends_on: "eval:doc.report_scope == 'Consolidated Group'",
		},
		{
			fieldname: "show_company_breakdown",
			label: __("Show Company Breakdown"),
			fieldtype: "Check",
			default: 1,
			depends_on: "eval:doc.report_scope == 'Consolidated Group'",
		},
		{
			fieldname: "cost_center",
			label: __("Cost Center"),
			fieldtype: "Link",
			options: "Cost Center",
		},
		{
			fieldname: "cash_budget_item",
			label: __("Cash Budget Item"),
			fieldtype: "Link",
			options: "Cash Budget Item",
		},
		{
			fieldname: "source_type",
			label: __("Source Type"),
			fieldtype: "Select",
			options: "\nAll\nJournal Entry\nPayment Entry",
			default: "All",
		},
		{
			fieldname: "show_details",
			label: __("Show Details"),
			fieldtype: "Check",
			default: 0,
		},
		{
			fieldname: "show_unclassified",
			label: __("Show Unclassified"),
			fieldtype: "Check",
			default: 1,
		},
		{
			fieldname: "show_intercompany",
			label: __("Show Intercompany Movements"),
			fieldtype: "Check",
			default: 1,
			depends_on: "eval:doc.report_scope == 'Consolidated Group'",
		},
		{
			fieldname: "show_internal_transfers",
			label: __("Show Internal Transfers"),
			fieldtype: "Check",
			default: 0,
		},
	],
};
